%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole" # Currently only Pinhole Model is supported

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 432.0433654785156
Camera.fy: 432.0433654785156
Camera.cx: 423.03424072265625
Camera.cy: 235.6173095703125

Camera.k1: -0.00859388429671526
Camera.k2: 0.04788520932197571
Camera.p1: -0.04412417113780975
Camera.p2: 0.008043156005442142

# Camera resolution
Camera.width: 848
Camera.height: 480

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from camera to body-frame (imu)
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [1, 0, 0, 0.03,
          0, 1, 0, -0.007,
          0, 0, 1, -0.016,
          0, 0, 0, 1]

   # data: [-0.9999680,  0.0000000,  0.0079999, 0.0,
   #       0.0000000, -1.0000000,  0.0000000, 0.032,
   #       0.0079999,  0.0000000,  0.9999680, 0.0,
   #       0.0, 0.0, 0.0, 1.0]

# Feature type. Currently only ORB and SIFT supported, for place recognition always ORB features are used
extractor.type: 'ORB' 
extractor.nFeatures: 1000 # 1000

#--------------------------------------------------------------------------------------------
# Frontend COVINS Parameters
#--------------------------------------------------------------------------------------------

# 1 if Odometry is published in IMU frame. Set to 0 if published in Camera Frame
odom_in_imu_frame: 1

#Minimum translational distance in metres for considering a new KF
t_min: 0.1

#Minimum rotational angle in radians for considering a KF. A new KF is generated if either of the
# translational or rotational condition is satisfied
r_min: 0.2


#--------------------------------------------------------------------------------------------
# SIFT Parameters
#--------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeaturesPR: 1000 # 1000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2
# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
