version: "3.9"
services:
  client:
    image: covins
    command: /bin/bash -c "cd ${CATKIN_WS}; source devel/setup.bash; roslaunch ORB_SLAM3 launch_docker_ros_euroc.launch ag_n:=${AGENT_NUM}"
    network_mode: "host"
    volumes:
      - ${CONFIG_FILE_COMM}:${CATKIN_WS}/src/covins/covins_comm/config/config_comm.yaml
      - ${LAUNCH_FILE}:${CATKIN_WS}/src/covins/orb_slam3/Examples/ROS/ORB_SLAM3/launch/launch_docker_ros_euroc.launch
      - ${DATA_FILE}:${CATKIN_WS}/src/covins/orb_slam3/Examples/Monocular-Inertial/replication.yaml
    environment:
      ROS_MASTER_URI: ${ROS_MASTER_URI}
      AGENT_NUM: ${AGENT_NUM}
